### ISSUE TITLE
bep20 token social update issue

### ISSUE THREAD

**Issue by madhuraja97** [vittominacori/bep20-generator#3]
i was generated bep20 token by vittominacori but when i was fill the social update form then binance smart chain exucitive reject my form they are said email are not owner email on contract regiter. not office website and email .. but i want to update my social and website on cotract address how can i solve

**Comment by vittominacori** [comment]
Hello you should follow their requirements https://bscscan.freshdesk.com/support/solutions/articles/67000221190-how-to-update-token-information-on-bscscan-

Contact their support if you have some issue.

**Comment by madhuraja97** [comment]
already filled and got this response 


Hi Madhusudanjoshi9922,
We have received your submission for the token information update. However, at this point in time, we are unable to update the token’s page due to lack of some information, or differences therein provided, required for our part.

Specifically, it appears that:
​
- There is no clear information available about the token/project,
- The project does not provide a transparent/clear information on its founder and team members (with supporting public 
   professional profiles i.e LinkedIn profile or equivalent),
- The sender’s email address is not the same as the token/project’s official domain
​
You may re-submit your update request once you have rectified the issues highlighted above.

*Kindly take note that although we are unable to update the token’s page, all pertinent information of the token, such as transactions, token supply, token holders, etc, are still publicly available for anyone to interact with.

**Comment by madhuraja97** [comment]
and how can get this Message Signature Hash * for verify ownership

**Comment by vittominacori** [comment]
Issues are with your email and project/team description.

Anyway you can verify token address by logging on bscscan and the go to verify page https://bscscan.com/verifyaddress.

Contact their support.
